# Use a minimal base image for the build stage
FROM gradle:7.3.3-jdk11 AS build

# Set the working directory for the application build
WORKDIR /app

# Copy essential build files for Gradle dependency resolution
COPY build.gradle settings.gradle ./

# Copy the Gradle Wrapper scripts
COPY gradlew .
COPY gradle gradle

# Download and resolve dependencies using the Gradle Wrapper
RUN ./gradlew dependencies

# Copy the application zip file into the image
COPY spring-boot-app.zip .

# Unzip the application zip file
RUN unzip spring-boot-app.zip

# Build the application using the Gradle Wrapper
RUN ./gradlew build --stacktrace

# Use a minimal base image for the runtime stage
FROM adoptopenjdk:11-jre-hotspot

# Set the working directory for the runtime
WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/build/libs/demo-0.0.1-SNAPSHOT.jar app.jar

# Expose the port on which the application runs
EXPOSE 8080

# Define the command to run the application
CMD ["java", "-jar", "app.jar"]
