# Path to the private key associated with the key pair used for EC2 instances.
# In a real environment, replace this with the actual path to your private key.
# SSH user for connecting to EC2 instances.
ansible_ssh_private_key_file: /path/to/your/dummy/key.pem
ansible_ssh_user: ec2-user
